### PR TITLE
Add p7zip manifest

### PR DESCRIPTION
**Pull request by cbm755**
Not used yet, will do another MR later

### CODE REVIEW

**Comment by ghisvail** [comment]
Looks good. Why the extra patching and files ? I made a quick search for `p7zip` in the flathub org and found a simpler module [definition](https://github.com/flathub/com.realm667.WolfenDoom_Blade_of_Agony/blob/9e1cf39a01a702908163a64ef24dd6d0cc07dec9/com.realm667.WolfenDoom_Blade_of_Agony.yaml#L22).

**Comment by ghisvail** [comment]
It is also fine to have all modules defined in a single manifest file. There aren't that many compared to other projects, anyway.

**Comment by cbm755** [comment]
It didn't compile for me without the patch...  or maybe that was before I tried cmake...  The fedora spec has lots of CVE patches too, but I assume because we do not expose the tool to user-supplied data we don't care.

I will try the simpler one in your link...

**Comment by ghisvail** [comment]
> I assume because we do not expose the tool to user-supplied data we don't care.

Let's say that we don't put the same constraints on modules as for native packages in a Linux distribution used on desktop and servers.

**Comment by ghisvail** [comment]
Thanks!

**Pull request merged**
